### ISSUE TITLE
when the new version will be released?

### ISSUE THREAD

**Issue by tianlijian** [distcc/distcc#163]
when will  the new version be released?

**Comment by Pinkbyte** [comment]
+1, something at least like 3.2_rc2 would be much appreciated

**Comment by TafThorne** [comment]
Soon I would hope.  It is something of a rubber stamping exorcise #159 Please badger me if I do not get this sorted out soon.

**Comment by afbjorklund** [comment]
If you **do** make new releases, I suggest getting off this "rc" track and back to usual versions.

Having something be a "release candidate" for years and years isn't really helping anyone...

**Comment by TafThorne** [comment]
Yer I do not think it was meant to be an RC for all that long. The main project developers kinda stopped or something and it was just the most recent thing posted.  It kind of truly reflects that a candidate release was  generated but not all the release criteria were checked of fulfilled.  

I think going forward people are happy to have the semantic v2 stuff, with a short lived rc included in that as the pre-release stage. There was a discussion about that in the mailing lists or another bug on here.

**Comment by heroxbd** [comment]
+1 please push out a release.

**Comment by dawagner** [comment]
I just stumbled on a puzzling bug fixed by 44e89fc437dee4f9b8da44bf5980fbcffee02889 (included in the 3.2 branch). A new release for distributions to package would be nice.

**Comment by wdelgenio** [comment]
Also the documentation describes DISTCC_IO_TIMEOUT as an optional environment variable, but from what I've seen, that option is not available in 3.1.  I've been trying to figure out why it wasn't working for me, then I checked the changelog.  Having 3.2 available via the ubuntu repo would be very nice.

**Comment by afbjorklund** [comment]
The 3.3 version has been released
