### ISSUE TITLE
Uninstall Needed ?

### ISSUE THREAD

**Issue by HackerTon** [distcc/distcc#165]
Hi,

Can I create a uninstall script for Distcc ?

**Comment by thedrow** [comment]
I think that uninstallation is managed by the package manager of your distribution.
What do you mean?

**Comment by HackerTon** [comment]
That is only if you install it from the package manager. I am talking about the fresh compile version. 
I wanted to create a script that uninstall distcc from the system. Which is the opposite of install-sh(make install).

**Comment by thedrow** [comment]
Sure. Go for it.
