### ISSUE TITLE
Can almost compile on Centos7 gcc 4.8.5

### ISSUE THREAD

**Issue by yarlB** [distcc/distcc#173]
changing -Wno-unused to -Wno-unused-parameter line 213 in configure.ac is sufficient

gcc -v is:
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configuré avec: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Modèle de thread: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)

**Comment by TafThorne** [comment]
It would be better to make the code more compliant to the fussy compilers than to make the compilers less fussy if possible.  Could you supply the failing compiler messages?

**Comment by yarlB** [comment]
I do not have the host under my hands anymore.
Anyway,
    The problem was that an unused parameter throwed a warning that was '-Werror'ed ('unused' attribute statements were commented if I remember well, whatever...).
    Here I tell gcc to ignore less warnings, and it still compiles, which I assume is fine.
    I guessed that the gcc I used wasn't supporting -Wno-unused, that's all. Not sure about that. I just posted some information about gcc that could be of use to someone (maybe).

**Comment by TafThorne** [comment]
The usual way to explicitly tell the compiler a C or C++ parameter is not being used in a function or method is to cast it to void at the start of the function.  

```C
void function (int a_param, int another_param)
{
    (void) another_param;
    a_param = 0;
}
```
At least I think that is how it is usually done.  It is better to not have the unused variable passed in at all but there are times it can be helpful.  

Your compiler was probably treating warnings as errors.  This is quite a common behaviour as it promotes better coding.

**Comment by yarlB** [comment]
Whatever. This is becoming irrelevant.
