### ISSUE TITLE
gdb can't find any source after compile through distcc

### ISSUE THREAD

**Issue by ooxxao** [distcc/distcc#181]
I'm using several freebsd machines, and all of them are in same version, 10.3-RELEASE i386.

And installed distcc every machine through ports, /usr/ports/devel/distcc/.

The distcc version is distcc-3.1.

Any compile was done very successfully, even in a very fast way as I expected.

But after I try to make break point in gdb, it cannot catch any source files of the project.

It may be the result of the temp files such as 'distccd_xxxxxx.ii' that distcc / distccd give and receive between machines.

I've tried 'directory' command in gdb, and it is not sufficient because my file tree is so complicated and too big.

gdb is just fine when I compiled it locally without distcc.

Is there any solutions for my situation?

**Comment by paranormal** [comment]
For now - not. It was compiled using another filenames, accordingly gdb can't be applied.

**Comment by ooxxao** [comment]
Is there any way to give original file-path?

**Comment by paranormal** [comment]
Probably not, or not simple solution.

**Comment by itensionanders** [comment]
I believe that the issue is related to using clang (with ELF), since gcc does give the correct name.
Probably it will need rewriting on the client side, similar to what pump mode does ? Or a clang fix.

**Comment by itensionanders** [comment]
gcc's elf:
`     1: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS hello.c`

clang' elf:
`     1: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS /tmp/distccd_bc4dfc6c.i`

**Comment by paranormal** [comment]
Seems I was wrong @ooxxao could you confirm?

**Comment by itensionanders** [comment]
i.e. something similar (in code) to what `./h_fix_debug_info <filename> <client-path> <server-path>` does:

```
./h_fix_debug_info[5917] (dcc_fix_debug_info) client_path_plus_slashes = hello.c////////////////
./h_fix_debug_info[5917] (update_section) ".debug_info" section of file hello.o has no occurrences of "/tmp/distccd_32630e24.i"
./h_fix_debug_info[5917] (update_section) updated ".debug_str" section of file "hello.o": replaced 1 occurrences of "/tmp/distccd_32630e24.i" with "hello.c////////////////"
```

**Comment by ooxxao** [comment]
Thanks . Now I know what was wrong. I'll try things above and comment again. Thanks again!

**Comment by ooxxao** [comment]
For now, I believe that the problem is related to the compiler I use (clang).
I'm trying to install gcc via port (/usr/ports/lang/gcc) but gcc can't compile any of my sources.
As I think, the finest way is to switch server-path to client-path as itensionanders said.
Could you tell me at which stage and what procedure I should do?
Or, if I use pump mode, the client machine just rename it properly, so this issue will over?

**Comment by ooxxao** [comment]
Actually pump mode doesn't word either.

**Comment by itensionanders** [comment]
@ooxxao : pump mode cleans up the _directory_. but you want to clean up the file name, too.
so it is similar, but not identical. however, you could try a sample file ? notice the temp directory in the server log (or run readelf on it afterwards), and then use the "h_fix_debug_info" on the object file. there is probably a simple src/serve.c patch to do this, but I haven't gotten around to trying it myself just yet.

**Comment by ooxxao** [comment]
After all of the compile was done? Ok, I'll try it
