### ISSUE TITLE
Can this run via AWS Lambda?

### ISSUE THREAD

**Issue by manglav** [distcc/distcc#189]
This may be a naive question, new to distributed compiling. I'm working on some ARM stuff, and compilations of large programs (like openCV) are slow.  If you upload the source code to Elastic File Storage (amazon's NFS), each node would have access.

**Comment by thedrow** [comment]
That's a very interesting question.
Can you make gcc/clang available on Lambda? What about ssh?

**Comment by afbjorklund** [comment]
If the nodes already have all the source code, wouldn't you just have to call the compiler then ?

Starting distcc servers in the cloud is definitely possible. Basically you only need the toolchain*.

* i.e. the compiler and assembler. Plus the default system headers, if using the "pump" mode.

The compiler can be a cross-compiler. For instance: a compiler for ARM, but running on x86_64.

e.g. http://packages.ubuntu.com/gcc-arm-linux-gnueabihf

Possibly set up a "gcc" link first in the path, for the distccd.

**Comment by manglav** [comment]
The goal would be to have near instantaneous compiles.  Lambda has a 5 min timeout, and can run any binaries you want. It would have to be cross-compiler, because lambda is x86.

I'm envisioning something like you upload your source code + toolchain, and 30 seconds later you have your binaries. I was just curious if there's something fundamentally preventing this.

This would be very helpful for cross compiling. I gave up cross compiling opencv on x86 because there were so many dependencies that were missing.

**Comment by afbjorklund** [comment]
You *can* run one compile per container. But it would probably mean a lot of overhead, compared with doing "a couple" in each ? For example, the default lifespan of a single distccd child is 50 compiles.

**Comment by manglav** [comment]
I'm not saying one compile per container. Rather I'm saying for large projects that you want to compile in ~4 minutes, distribute to X nodes on Lambda.  Each node can do as many compiles as possible within the 4 minutes.

**Comment by sourcefrog** [comment]
I think it would be more practical to start real VM images through autoscaling, which can have the relevant compilers in the image and can run the distccd binary directly.

**Comment by manglav** [comment]
I believe autoscaling would be more expensive than lambda.  Maybe using AWS's new batch jobs on Spot instances, but you would still need a coordinator. But this seems possible, so the question has been answered, so I'll close it. Thanks all!

**Comment by chadbrewbaker** [comment]
I have gcc working AWS Lambda and reading/writing from an S3 bucket. Interested in getting something like distcc working. Ideally you would tag build artifacts with timestamps of how long they take then load each lambda up with 2/3 of what it can chew on in five minutes.

Is there an existing distcc workflow that allows you ssh into client build helper boxes, copy over files, build, then copy back artifacts?

**Comment by manglav** [comment]
@chadbrewbaker, this is sort of unrelated, but a pet project of mine is mounting EFS from a lambda. Stay tuned 😄

**Comment by lipi** [comment]
A Thunk to Remember: make -j1000 (and other jobs) on functions-as-a-service infrastructure
http://stanford.edu/~sadjad/gg-paper.pdf

**Comment by shawnl** [comment]
Distcc has no dependencies besides libc, if that is what you are asking.

Otherwise I have little interest in propritary and vendor lock-in
platforms. Yes, I know it can be billed in 100ms increments, but Google
cloud is 1sec increments and doesn't have the vendor lock-in.

Sorry to be a crank, but the Amazon page on Lambda was so full of
bull-shit, like "server-less apps". I agree with Larry Ellison that "cloud
computing" is a bunch of bull-shit https://youtu.be/0FacYAI6DY0
