### ISSUE TITLE
Distcc with zeroconf not working properly together with ninja

### ISSUE THREAD

**Issue by gustafullberg** [distcc/distcc#208]
When using distcc with zeroconf and the ninja build system, each C module takes about 25 seconds to compile.

The problem is that distcc forks a new background daemon to take care of zeroconf callbacks for finding slaves. When the "normal" distcc process completes compilation it enters zombie state and is not reaped by ninja until the background daemon times out and exits (which takes ~25 seconds).

The reason for waiting for the damon seems to be an open file descriptor in the daemon process. I have a local fix that closes all file descriptors in the daemon and then it works as expected.

I will follow up with a pull request fixing the issue.

How to reproduce:

```
$ distccd --daemon --zeroconf --allow 10.0.0.0/8

$ cat /etc/distcc/hosts
+zeroconf

$ cat main.c
#include <stdio.h>

int main()
{
        return 0;
}

$ cat build.ninja
rule cc
  command = distcc -c $in

build main.o: cc main.c

$ time ninja
[1/1] distcc -c main.c

real    0m26.581s
user    0m0.017s
sys     0m0.000s
```

**Comment by gustafullberg** [comment]
#209 Pull request for fixing the issue

**Comment by shawnl** [comment]
#209 was merged
