### ISSUE TITLE
Position of expandargv() in distcc.c

### ISSUE THREAD

**Issue by NilunaRay** [distcc/distcc#218]
When using distcc(version 3.2rc1 with a patch based on 214838b742467896aa19f9bb5546b0ca23ad80be ) with command line including response files(*.rsp), following error is shown at client-side computer and distcc fails.

> path overflowed in dcc_abspath()

I noticed that `path_len` arguments of `dcc_abspath()` in [src/utils.c](https://github.com/distcc/distcc/blob/master/src/util.c) is random and large value when this error occurs.
This function is called by following code in [src/climasq.c](https://github.com/distcc/distcc/blob/master/src/climasq.c)
```C
/* Filter PATH to contain only the part that is past our dir.
 * If we were called explicitly, find the named dir on the PATH. */
if (progname != argv[0]) {
    findpath = dcc_abspath(argv[0], progname - argv[0] - 1);
    findlen = strlen(findpath);
} else {
    findpath = NULL;
    findlen = 0;
}
```

At this point, `compiler_name` in `main()` in [src/distcc.c](https://github.com/distcc/distcc/blob/master/src/distcc.c) have been passed to `dcc_support_masquerade()` as `progname`.
When distcc is executed with response file arguments, `compiler_name` is calculated with original (not expanded) `argv` in `main()` in src/distcc.c because `compiler_name = (char *) dcc_find_basename(argv[0]);` is before `expandargv(&argc, &argv);`.
So, in this situation, `progname - argv[0] - 1` is invalid value as `path_len` of `dcc_abspath()`.

I think, `expandargv()` should called before `compiler_name` is calculated?

(In my environment, changing order of these statements solves the error.)

**Comment by thinrope** [comment]
This smells like a bug, but can you actually show/attach the patch that makes it work for you?

**Comment by NilunaRay** [comment]
Yes, attached.

```Diff
--- a/src/distcc.c
+++ b/src/distcc.c
@@ -241,12 +241,12 @@
 
     dcc_trace_version();
 
-    compiler_name = (char *) dcc_find_basename(argv[0]);
-
-#if HAVE_LIBIBERTY    
+#if HAVE_LIBIBERTY
     /* Expand @FILE arguments. */
     expandargv(&argc, &argv);
 #endif
+
+    compiler_name = (char *) dcc_find_basename(argv[0]);
  
     /* Ignore SIGPIPE; we consistently check error codes and will
      * see the EPIPE. */

```

This simply changes call order of `expandargv()` and `dcc_find_basename()`.
Applting this, I can now successfully do remote compile with response files.

**Comment by shawnl** [comment]
given that libiberty is broken, why don't we just remove it and get rid of the dependency?

**Comment by NilunaRay** [comment]
This code is for support compiling with response files. In compiler, this function is implemented by libiberty. So, this dependency is needed for users who want such functionality.
Of course, implementing equivalent code in distcc can be possible solution to remove dependency to libibery.

At least in this issue, broken code is in distcc, not libiberty.

**Comment by NilunaRay** [comment]
Thank you for fixing!

**Comment by shawnl** [comment]
This is part of distcc 3.2
