### ISSUE TITLE
releases should have configure files already generated

### ISSUE THREAD

**Issue by shawnl** [distcc/distcc#237]
you should run ./autogen.sh before making a tarball. That way the portability of autotools is realized.

I just built ON android with temux (patch incoming), but this bug was a PITA. https://github.com/termux

**Comment by afbjorklund** [comment]
Releases do have all files generated, courtesy of "make dist".
Just that there has been no distcc release from github yet...

The old dist files are still available from the *old* site:
https://code.google.com/archive/p/distcc/downloads

**Comment by shawnl** [comment]
https://github.com/distcc/distcc/archive/v3.2rc1.tar.gz
does not contain ./configure

The old dist files do

**Comment by afbjorklund** [comment]
Those "archive" files are auto-generated by GitHub, from the git tags. So they are just like a checkout ?

We should get @TafThorne to update the old dist files as well, and to make new ones too (eventually)

**Comment by shawnl** [comment]
>  So they are just like a checkout ?
man git archive

**Comment by afbjorklund** [comment]
As in: no dist files built, in those

**Comment by afbjorklund** [comment]
I _think_ this is what was mentioned as #213, even though it applies to both legacy and future builds.
