### ISSUE TITLE
Move the home page to GitHub Pages

### ISSUE THREAD

**Issue by afbjorklund** [distcc/distcc#241]
https://pages.github.com/

i.e. https://distcc.github.io

The current workaround* looks silly, and the old domains seems to be pointing to github project for now...
(http://distcc.samba.org, distcc.org). Would be nice to gather all the old pages under a real web site again

https://cdn.rawgit.com/distcc/distcc/9a09372bd3f420cdd7021e52eda14fa536a3c10e/doc/web/index.html

**Comment by shawnl** [comment]
Also mention that clang is supported.

**Comment by TafThorne** [comment]
So I need to take the website generated stuff and put it into the GitHub pages thingy as a release instead of the current head of tryy rawgit.com stuff?  I'll assign this to myself and see if I have the required powers to do so.

**Comment by manhnt9** [comment]
You can create another repo to store .html files to host a web on GitHub

**Comment by thedrow** [comment]
@TafThorne Anything you need my help for?

**Comment by shawnl** [comment]
@thedrow you need to create a new repository named distcc.github.io

https://pages.github.com/

**Comment by thedrow** [comment]
Will do :+1:

**Comment by thedrow** [comment]
@shawnl Done :smile:

**Comment by shawnl** [comment]
Now invite me to collaborate on it.

**Comment by thedrow** [comment]
Also done.

**Comment by shawnl** [comment]
https://distcc.github.io/

**Comment by shawnl** [comment]
I've also set it up so you can change the dns and make it http://distcc.org/

**Comment by thedrow** [comment]
I don't own the domain unfortunately. I wonder who does.

**Comment by shawnl** [comment]
I had to turn that off, cause it was redirecting to distcc.org which then redirects quite uselessly to github. (you have to set up dns first)

I would presume @sourcefrog owns the domain.

**Comment by afbjorklund** [comment]
Nice!

**Comment by sourcefrog** [comment]
Hi, I do own that domain. lmk where you'd like me to point it.

**Comment by shawnl** [comment]
point A records to 
`
    192.30.252.153
    192.30.252.154
`
see https://help.github.com/articles/using-a-custom-domain-with-github-pages/ and https://help.github.com/articles/troubleshooting-custom-domains/#dns-configuration-errors

then set the custom domain here https://github.com/distcc/distcc.github.io/settings

**Comment by sourcefrog** [comment]
ok will do

**Comment by sourcefrog** [comment]
I just saw this issue again 😮 

I have made the DNS and config changes. It will take a little while to propagate...

**Comment by sourcefrog** [comment]
DNS is redirected and seems to be working. I will try to turn on HTTPS.

**Comment by sourcefrog** [comment]
Looks like it is still waiting for a LetsEncrypt certificate, or maybe in the process of rolling it out.

**Comment by TafThorne** [comment]
I may have not kept track of this project for a bit.  Sorry about that.  Glad to see that Martin is back on the case!

**Comment by sourcefrog** [comment]
Finally done! HTTPS is on.
