### ISSUE TITLE
How to disable distcc compling on localhost?

### ISSUE THREAD

**Issue by WenbinHou** [distcc/distcc#299]
I'm not sure whether this is my fault or am I missing something...

There are always 4 cc1plus run by distcc on localhost, even if I don't specify localhost in DISTCC_HOSTS.
How can I disable distcc running cc1plus on localhost?

TIA!

**Comment by TafThorne** [comment]
Can you share your command line and the number of processes you are executing (which may relate to the number of cores on your machine).  Not all the work can easily be done remotely as the central machine is the one with the full view of the image.  These may be to do with working out what files to send.

**Comment by shawnl** [comment]
use `DISTCC_FALLBACK=0`
