### ISSUE TITLE
distcc fails to compile latest Linux kernel due to lack of asm-goto support

### ISSUE THREAD

**Issue by LarBob** [distcc/distcc#300]
When attempting to compile kernel 4.17.12, the compile immediately fails with this:
`arch/x86/Makefile:184: *** Compiler lacks asm-goto support..  Stop.`
I am running the make command like this:
`pump make -j24 CC=distcc`
I am using GCC 6.3.0 on Debian. GCC 6.3.0, which supports asm-goto, is what's being used by distcc, which I can see by running distcc -v.

**Comment by shawnl** [comment]
Did you try without pump?

I have been compiling 4.18 without problems.

**Comment by shawnl** [comment]
if your distcc server has differn't header files then pump cannot work correctly. It could be that your distcc server doesn't support asm-goto.

**Comment by LarBob** [comment]
With and without pump I get the same thing. Both machines are almost exact copies of each other.

**Comment by LarBob** [comment]
Er, this was due to distcc using clang instead of gcc I believe.
Resolved now. Sorry for wasting your time.
