### ISSUE TITLE
Include server in pump mode produces 'bogus escape (end of line)' error

### ISSUE THREAD

**Issue by ramelsberger** [distcc/distcc#305]
If a *.cpp file contains something like 
char* psz = "c:\\tmp\\"; 
then the include server will give up analyzing and the system will exit the pump mode for the rest of the compilation. This seems to be due to some problems with regular expressions, which is a kid of sad, because the rather effective pump mode cannot be used any longer, even though the source code is perfectly legal C syntax.
Is this a known problem, or is there a workaround?

**Comment by afbjorklund** [comment]
This code doesn't compile with either gcc nor clang, so I **don't** think it's legal syntax.
You will need to escape those backslashes, and make it a pointer while you are at it...

``` C++
char *psz = "c:\\tmp\\";
```

**Comment by ramelsberger** [comment]
Thanks for the answer. Of course, you are absolutely right, and in the source code I had the double backslashes. This seems to be some copy-paste problem. But even then the original problem exists.

Mit freundlichen Grüßen / Best regards
Klaus Ramelsberger

R&D Platform Software
Rohde&Schwarz GmbH & Co. KG
Test and Measurement Division

P. O. Box 80 14 69, 81614 Munich
Muehldorfstrasse 15, 81671 Munich
Germany
Phone: +49 89 4129-12226
Fax: +49 89 4129-62226
Internet: www.rohde-schwarz.com<http://www.rohde-schwarz.com/>


Geschäftsführung / Executive Board: Christian Leicher (Vorsitzender / Chairman), Peter Riedel, Sitz der Gesellschaft / Company's Place of Business: München, Registereintrag / Commercial Register No.: HRA 16 270, Persönlich haftender Gesellschafter / Personally Liable Partner: RUSEG Verwaltungs-GmbH, Sitz der Gesellschaft / Company's Place of Business: München, Registereintrag / Commercial Register No.: HRB 7 534, Umsatzsteuer-Identifikationsnummer (USt-IdNr.) / VAT Identification No.: DE 130 256 683, Elektro-Altgeräte Register (EAR) / WEEE Register No.: DE 240 437 86

**Comment by shawnl** [comment]
Re-open if you can provide a better testcase
