### ISSUE TITLE
Linux Kernel Assembly Macros

### ISSUE THREAD

**Issue by lsgunth** [distcc/distcc#312]
Hi,

As of v4.20-rc1 distcc (and icecc for that matter) can no longer be used to distribute a compile of the linux kernel for x86. See this [thread](https://lore.kernel.org/lkml/89262174-6f15-6116-e67f-436f7c1bfe99@deltatee.com/T/#u).

The problem is the kernel is now adding "-Wa,macros.s" argument to every compile option so that specific assembly macros can be used in inline assembly code across the kernel. When distcc sees this, any remote builds will fail seeing it won't be able to find macros.s and it will fallback to a local build.

Is there any way this could be supported by distcc as there does not appear to be a good solution in the kernel?

Thanks,

Logan

**Comment by TafThorne** [comment]
Could you not add them to _every_ compile option but selectively when needed?  Then distcc would only fail the ones with it.  
Thank you for including the link tot he discussion thread, it helps to flesh out the problem space.

**Comment by lsgunth** [comment]
It would be too difficult to determine which sources use the macros. The assembly macros will be used in common kernel defines (like WARN()) which are called throughout the kernel. So even if one could determine which files need them there'd probably be a significant fraction of compiles that could not be distributed.

There's more background on the motivation for this [here](https://nadav.amit.zone/linux/2018/10/10/newline.html)

And the discussion on the best way to apply the global assembly file is [here](https://lkml.org/lkml/2018/5/18/1029).

**Comment by afbjorklund** [comment]
The include_server is able to handle both `-include` and `-imacros` today. One could implement `-Wa,macros.s` as a special case of this, perhaps ? Then it will also be sent to the distccd server...

https://github.com/distcc/distcc/blob/master/include_server/parse_command.py#L105

**Comment by afbjorklund** [comment]
Yeah, this patch seems to work for my simple hello world program:

``` diff
diff --git a/include_server/parse_command.py b/include_server/parse_command.py
index cd02d01..bacf250 100755
--- a/include_server/parse_command.py
+++ b/include_server/parse_command.py
@@ -158,6 +158,7 @@ CPP_OPTIONS_ONE_WORD = {
   '-undef':         lambda ps, arg: None,
   '-nostdinc':      lambda ps: ps.set_nostdinc(),
   # TODO(csilvers): deal with -nostdinc++ as well?
+  '-Wa,macros.s':   lambda ps: ps.include_files.append('macros.s'),
 }
 
 # These are the cpp options that are one letter long, and take an
```

Not sure if that single filename is enough, or if there were more too ?
