### ISSUE TITLE
Distcc fails to distribute if compilation and linking is done in single command

### ISSUE THREAD

**Issue by ftialok** [distcc/distcc#314]
Hello Guys,

I'm trying to build multiple open-source projects, and to speedup compilation i'm using distcc.

Everything works great till i reached to project which have implemented make file in such a way that compilation and linking is done with single command. In this case distcc just ignores distribution and does compilations locally. (I've gone through forums and post and found this is expected behaviour).

Please suggest if there are any workaround to tell distcc or update in make file to distribute compilation part and linking locally. Please suggest if there are any other tools that can work in such cases.

Thanks,
Alok

**Comment by afbjorklund** [comment]
Update the make file, to separate the compilation and the linking. Most standard gnu makefiles and automake do this by default.

**Comment by ftialok** [comment]
> Update the make file, to separate the compilation and the linking. Most standard gnu makefiles and automake do this by default.

Thank you, i'm going to to look into make files and see at what level i can automate this process.
