### ISSUE TITLE
Distcc server not accepting more than 8 requests

### ISSUE THREAD

**Issue by hkrpavan** [distcc/distcc#318]
Distcc server not accepting more than 8 requests.

I have three 24 CPU servers configured as distcc servers (3.2). Client is originating requests in pump mode with /LIMIT as 24. Even then i always see servers accepting 8 requests at a time. These servers have plenty of memory and cpus un utilized.

**Comment by shawnl** [comment]
Fixed in https://github.com/distcc/distcc/commit/2637e6fcab374b04b71fcfaf7c76886abe810fd1
