### ISSUE TITLE
Remove Martin Pool's email from AUTHORS file

### ISSUE THREAD

**Issue by danboid** [distcc/distcc#326]
After failing to find a solution online to my poor performance from distcc, I decided to write to Martin because he is the original author of dist but more importantly he is the only person whose email is listed in the distcc AUTHORS file. Martin replied saying that he hasn't worked on distcc for over a decade now and so to avoid anyone else making the same mistake and sending him questions about distcc I think it best his email be removed from the AUTHORS file.

**Comment by TafThorne** [comment]
Seems a reasonable request.

**Comment by TafThorne** [comment]
The code to remove Martin Pool's email address has been merged in.
