### ISSUE TITLE
HEAD will not compile util.o (-Werror=sign-compare)

### ISSUE THREAD

**Issue by XenHat** [distcc/distcc#337]
Current repository HEAD (https://github.com/distcc/distcc/tree/25b7f89875c303f01754557e82e08a6c052875d8) will not compile due to a sign comparison:

```
src/util.c: In function ‘sd_is_socket’:
src/util.c:1007:23: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
                 if (l < sizeof(sa_family_t))
                       ^
cc1: all warnings being treated as errors
make: *** [Makefile:458: src/util.o] Error 1

```

Build configuration: `--enable-pump-mode`
Environment: Cygwin x86_64, gcc (GCC) 7.4.0

**Comment by shawnl** [comment]
Please let me know if that fixes it.

**Comment by XenHat** [comment]
That is indeed fixed. However, it cannot install. See #338
