### ISSUE TITLE
No log when -fplugin or -spec parameters are used

### ISSUE THREAD

**Issue by DirtYiCE** [distcc/distcc#343]
It took me a while to figure out why doesn't my kernel compilation works through distcc. Logs looks like something like this:
```
distccd[24617] (dcc_check_compiler_masq) /usr/bin/armv7a-unknown-linux-gnueabihf-gcc is a safe symlink to /usr/x86_64-pc-linux-gnu/armv7a-unknown-linux-gnueabihf/gcc-bin/8.3.0/armv7a-unknown-linux-gnueabihf-gcc
distccd[24617] (dcc_check_compiler_whitelist) armv7a-unknown-linux-gnueabihf-gcc in/usr/lib/distcc whitelist
distccd[24617] (dcc_cleanup_tempfiles_inner) deleted 5 temporary files
distccd[24617] (dcc_job_summary) client: 10.248.117.169:59478 OTHER exit:0 sig:0 core:0 ret:0 time:1592ms
```
It just mentions that the compiler is in the whitelist, then the next thing logged is deleting temporary files. Looking at the code we can see it's just a single goto to a common error handling part:
https://github.com/distcc/distcc/blob/c77c62651b8974b8d3c738467138250078c112fe/src/serve.c#L770

**Comment by shawnl** [comment]
Ahh yes, I guess these should be allowed when --enable-tcp-insecure is passed.

**Comment by DirtYiCE** [comment]
But wouldn't that require extra logic though? You need to copy the plugin file too and it obviously won't work if the server and the client is running on a different architecture.
I'd be happy with a single log that states you can't distcc this file because it uses -fplugin instead of silently failing.

**Comment by shawnl** [comment]
yeah it would try to use a file on the other side that wouldn't be there. (which is what it did before I added that logic).

Thanks for letting me now that I didn't add this bug :), because it never worked.
