### ISSUE TITLE
Bug: hardcoded limit of CPU usage for machines above 50 CPUs

### ISSUE THREAD

**Issue by pavsa** [distcc/distcc#348]
We're using distcc to locally preprocess and remotely compile sources. 

I've found out on our 64 core machine that distcc never creates more than around 50 concurrent preprocessor instances no matter what the localslots_cpp is set to. CPU usage was never approaching 100%.

I've discovered it is due to some arbitrary hardcoded limit of 50 slots in the following code:

https://github.com/distcc/distcc/blob/dc5f382365143d268a392afa5ce7456a600f4457/src/where.c#L176-L194

This limits both local preprocessor instances to 50 and each of the remote hosts to max 50 used compile instances per host as they use the same function to get the lock (```dcc_lock_one```).

I've increased this number above the number of cores and it solved the problem. CPU usage is now 100%.

Is there any reason for the value of 50? Git-blame shows it was added in 2008, so I guess it was enough back then, but now it's not uncommon have more than 50 cores in one machine.

Ideally this number should be set to:
```max ( local_cpus,  max( host1_slots, host2_slots, ... ) ) ```
to avoid idle cpu of both local and remote hosts.

**Comment by afbjorklund** [comment]
It also defaulted to 4 jobs per server, so I think it is mostly showing its age...

``` C
    /* Run only two tasks on localhost by default.
     *
     * It might be nice to run more if there are more CPUs, but determining
     * the number of CPUs on Linux is a bit expensive since it requires
     * examining mtab and /proc/stat.  Anyone lucky enough to have a >2 CPU
     * machine can specify a number in the host list.
     */
    hostdef->n_slots = 2;
```

``` C
        /* Default task limit.  A bit higher than the local limit to allow for
         * some files in transit. */
        curr->n_slots = 4;
```

It also kills each child after 50 compiles. So there's some "50" magic involved.

``` C
/**
 * Fork a child to repeatedly accept and handle incoming connections.
 *
 * To protect against leaks, we quit after 50 requests and let the parent
 * recreate us.
 **/

```

**Comment by pavsa** [comment]
#351 might be a better solution.
Just increasing the number of cpus does not break the outer ```for``` loop if all hosts in ```hostlist``` have ```n_slots``` less than ```i_cpu```.
