### ISSUE TITLE
New release 3.3.3

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [distcc/distcc#357]
Hi,

You seems to have committed a few fixes since the last release 3.3.2 from last year. Do you think it is worth doing a release 3.3.3 now or you wait some more content to be upstreamed ?

Cheers,
Romain

**Comment by Murazaki** [comment]
At least push a fix for this simple cast missing that breaks the install in `src/util.c:1000:23`.

**Comment by shawnl** [comment]
@Murazaki can you paste the error? I don't see any problem there 

```
int sd_is_socket(int fd, int family, int type, int listening) {
        int r;

        if (family < 0)
                return -EINVAL;

        r = sd_is_socket_internal(fd, type, listening);
        if (r <= 0)
                return r;
```

**Comment by Murazaki** [comment]
I'm talking about your last release, 3.3.2, and the comparison between socketlen_t and size_t.

**Comment by shawnl** [comment]
So it is fixed in master?

**Comment by shawnl** [comment]
ahh I see 251dad7977a811af39bbb

**Comment by shawnl** [comment]
fixed
