### ISSUE TITLE
Building Kernel >=5.2.0 fails to distribute out but 5.1.x builds fine

### ISSUE THREAD

**Issue by graysky2** [distcc/distcc#358]
Has anyone else noticed that compiling linux kernel 5.1.16 works fine with distcc but >=5.2.0 fails to distribute jobs?  I'm thinking there is something in the upstream code that isn't honoring the old definitions?

Example trying to compile 5.2.0:
```
...
distcc[22629] (dcc_readx) ERROR: unexpected eof on fd5
distcc[22629] (dcc_r_token_int) ERROR: read failed while waiting for token "DONE"
distcc[22629] (dcc_r_result_header) ERROR: server provided no answer. Is the server configured to allow access from your IP address? Is the server performing authentication and your client isn't? Does the server have the compiler installed? Is the server configured to access the compiler?
distcc[22629] Warning: failed to distribute scripts/mod/devicetable-offsets.c to 10.1.1.102/5, running locally instead
distcc[22635] (dcc_readx) ERROR: unexpected eof on fd5
distcc[22635] (dcc_r_token_int) ERROR: read failed while waiting for token "DONE"
distcc[22635] (dcc_r_result_header) ERROR: server provided no answer. Is the server configured to allow access from your IP address? Is the server performing authentication and your client isn't? Does the server have the compiler installed? Is the server configured to access the compiler?
distcc[22635] Warning: failed to distribute scripts/mod/empty.c to 10.1.1.102/5, running locally instead
...
```

Whatever is causing this breakage, it has not been backported to the 4.19-lts series.  I can build 4.19.61 with distcc working just fine.   I found an older discussion on [lkml](https://lkml.org/lkml/2018/11/15/467]) about similar but the date of this being 8+ months ago doesn't seem right.

My systems are running Arch Linux.
* distcc 3.3.2
* compiler 9.1.0

**Comment by shawnl** [comment]
can you use DISTCC_VERBOSE=1? The most probable reason is that use of magic comments to mark switch statements that fall through.

https://lkml.org/lkml/2019/6/24/1310

I and other's have complained, and you should too.

**Comment by graysky2** [comment]
@shawnl - Thanks for the quick reply.  [Here](https://gist.githubusercontent.com/graysky2/78aa03e2db38e68d2437bfaafabe75f7/raw/c37d1c4ae18e142fbba4a0ba2dd7c2475b04ad97/gistfile1.txt) is a few thousand lines with the `DISTCC_VERBOSE=1` var exported.  Does it confirm your suspicion?

**Comment by shawnl** [comment]
No, that doesn't appear to be it (although that log is useless). They are only looking at enabling that in 5.3 (and it wasn't merged, so maybe 5.4 now) There is also DISTCC_VERBOSE=1 on the host, and you can also use V=1 to have make print the commands.

**Comment by graysky2** [comment]
I added an `export DISTCC_VERBOSE=1 V=1` on the host (client, the machine doing the compiling).  I also enabled debug level logging on both the client and the volunteer.

[Build log ](https://gist.github.com/graysky2/f31a1717429174105f6906741912375f)on client
[Distccd log](https://gist.github.com/graysky2/573877e69953bc47fbd2bca24c74a01b) on client
[Distccd log](https://gist.github.com/graysky2/88bacb6d7213951ba6ec4c3762021e8b) on volunteer

Thanks for any insights.

**Comment by shawnl** [comment]
Its only failing on parse-options.c, and it should be printing the error, which distcc sent to it
distcc[14421] (dcc_r_token_int) got SERR0000018e
but apparently Kconfig is blocking it from printing that.

**Comment by graysky2** [comment]
I think if this is happening for me it would be affecting others building the 5.2.x series... I am unsure what I can do to fix it.

**Comment by shawnl** [comment]
Well you should get that error message (which is 0x18e bytes long).

**Comment by graysky2** [comment]
Is there anything to modify on the distcc side or is this completely a kernel issue?

**Comment by shawnl** [comment]
I can't tell without the error message that I was talking about.

**Comment by graysky2** [comment]
Is there a more verbose log level I can enable?

**Comment by shawnl** [comment]
There is no encryption, so you could use wireshark (make sure to turn off compression, which you have on)

**Comment by graysky2** [comment]
I can try it but since compiling 5.1.x works, other software works, it's just the 5.2.x series that doesn't, isn't it safe to assume there's something in that code (the 5.2.x kernel) that is not playing nice with distcc?

**Comment by graysky2** [comment]
@shawnl - Wireshark log is [here](https://gist.github.com/graysky2/caeb53acc6f713013e8810f00931bd13).  Thanks for the insights.

**Comment by graysky2** [comment]
@shawnl - Any insights?

**Comment by graysky2** [comment]
@shawnl - I think I see what's causing this....

If I build like this, I get the errors:
```
% export DISTCC_HOSTS="localhost/9 10.1.1.102/5"
% export PATH="/usr/lib/distcc/bin:$PATH"
% make -j15 bzImage
```

But if I build like this it works fine:
```
% export DISTCC_HOSTS="localhost/9 10.1.1.102/5"
% make -j15 bzImage CC=distcc
```

Why would that be?

**Comment by graysky2** [comment]
@shawnl - I think this has to be something with the linux upstream code not playing well with distcc

```
% export DISTCC_HOSTS="localhost/9 10.1.1.102/5"
% export PATH="/usr/lib/distcc/bin:$PATH"
% make -j15 bzImage
...
distcc[1823717] ERROR: compile parse-options.c on 10.9.8.112/5 failed
distcc[1823717] (dcc_build_somewhere) Warning: remote compilation of 'parse-options.c' failed, retrying locally
distcc[1823717] Warning: failed to distribute parse-options.c to 10.9.8.112/5, running locally instead
distcc[1823717] (dcc_please_send_email_after_investigation) Warning: remote compilation of 'parse-options.c' failed, retried locally and got a different result.
```

**Comment by graysky2** [comment]
@shawnl - I think this has to be something with the linux upstream code not playing well with distcc

```
% export DISTCC_HOSTS="localhost/9 10.1.1.102/5"
% export PATH="/usr/lib/distcc/bin:$PATH"
% make -j15 bzImage
...
distcc[1823717] ERROR: compile parse-options.c on 10.9.8.112/5 failed
distcc[1823717] (dcc_build_somewhere) Warning: remote compilation of 'parse-options.c' failed, retrying locally
distcc[1823717] Warning: failed to distribute parse-options.c to 10.9.8.112/5, running locally instead
distcc[1823717] (dcc_please_send_email_after_investigation) Warning: remote compilation of 'parse-options.c' failed, retried locally and got a different result.
```

BUT ... I get no such errors if a simply append `CC=distcc` like so:
```
% make -j15 bzImage CC=distcc`
```

**Comment by brian-mccarter** [comment]
I ran into this bug compiling linux-5.4.2 on armv7a-unknown-linux-gnueabihf running gcc-9.2.0 and distcc-3.3.3.  Jobs are sent to another machine running distccd with a crossdev toolchain.  The distcc server refuses to compile, with lots of errors like this:
```
Dec 13 09:12:53 my-machine distccd[3068384]: (dcc_run_job) Warning: -fplugin= and/or -specs= passed, which are insecure and not supported.
Dec 13 09:12:53 my-machine distccd[3068384]: (dcc_job_summary) client: X.X.X.X:55522 OTHER exit:0 sig:0 core:0 ret:0 time:1114ms
```
The kernel build was inserting lots of `fplugin` directives into the compile jobs.  I found that I could disable that behavior by modifying `arch/arm/Kconfig` in the source tree and deleting this line:
```
     select HAVE_GCC_PLUGINS
```
That did the trick.  I expect there is a similar fix for other architectures.

**Comment by shawnl** [comment]
`     select HAVE_GCC_PLUGINS`

This is the correct fix. Distcc cannot support GCC plugins due to technical reasons.

**Comment by graysky2** [comment]
@brian-mccarter - Interesting find.... did you see my post above about adding `CC=distcc` and `CXX=distcc` which on my system works as well.

**Comment by brian-mccarter** [comment]
@graysky2 - The critical parameter is `CONFIG_GCC_PLUGINS`, which depends on `CONFIG_HAVE_GCC_PLUGINS` and `CONFIG_PLUGIN_HOSTCC`.  None of those are editable through `menuconfig`.  

I tried editing `.config` manually to set `CONFIG_PLUGIN_HOSTCC=''`, but it gets reset back to `=g++` on `make`.  Same with manually setting `CONFIG_GCC_PLUGINS=n`.  It gets reset to `=y` on `make` because `arch/arm/Kconfig` has `select HAVE_GCC_PLUGINS`.  Deleting that line was the only way I found to permanently disable `CONFIG_GCC_PLUGINS`.

**Comment by graysky2** [comment]
@brian-mccarter - I found a work-around:
```
make -j30 all CC=distcc CXX=distcc
```

However, this is incompatible with ccache and distcc.  Your solution, to remove that line from "select HAVE_GCC_PLUGINS" line from in my case `arch/x86/Kconfig` seems to do the trick!

**Comment by shawnl** [comment]
> make -j30 all CC=distcc CXX=distcc

This only works because it screws up Kconfig's detection of GCC, as
--version now prints distcc's version string instead of gcc's. The "select
HAVE_GCC_PLUGINS" solution is the correct one.

**Comment by FlorianHeigl** [comment]
ran into this today (and I suspect last year, when I just had to give up)
can there be any way to have this without modifying the kernel?
How about if I sent a PR with a notice for the man page?
