### ISSUE TITLE
distcc rpm is missing in CentOS 8 repository

### ISSUE THREAD

**Issue by prasadz** [distcc/distcc#372]
Hi,

distcc rpm is missing in CentOS 8 repository. I googled it but did not find any resolution so I am asking this question here. Why distcc is not included in CentOS 8 repository?

Thanks.

**Comment by shawnl** [comment]
It is probably in EPEL (Extra packages for enterprise Linux), don't know how that works in Centos, and now that Centos is owned by RedHat.....
