### ISSUE TITLE
How to limit the number of preprocessor instances that run in parallel.

### ISSUE THREAD

**Issue by nicber** [distcc/distcc#393]
I'm using a 64 cores server as my distcc server.
I have a laptop with 4 cores.

I run `make -j64` to fully take advantage of the server, but that means that make will launch 64 distcc instances.
This, in turn, means my poor laptop will be running 64 preprocessors in parallel.

Is it possible to limit the number of concurrent preprocessor instances to 4 while running up to 64 jobs in the server?

Thanks for this great software.

**Comment by shawnl** [comment]
You can use pump mode to push the preprocessing to the servers, however pump mode is not recommended or supported.

In my experience compiling C (with C++ you may have different results) the laptop would handle this just fine, but your wifi is where you will probably have problems first.

**Comment by shawnl** [comment]
Oh, I see what you are asking for. Linux's scheduler should handle this fine, and you have been too lazy to run any tests.

**Comment by nicber** [comment]
No, the problem is RAM usage. The scheduler handles the load just fine, as you said.

I'm compiling many files that include a big C++ (30 MB) auto-generated header file. Each preprocessor instance uses 200 MB of RAM, which means a peak of 12.8 GB.

**Comment by shawnl** [comment]
Oh yes, I do remember that distcc has an option for this, although I forget what it is called ATM.

`--localslots_cpp=<int>` as documented in the man page.

**Comment by nicber** [comment]
Great, I had not seen that part of the manual. Thank you.

It is unfortunate that it does not work with ccache. Without ccache it works great.
This is my setup:
```
DISTCC_IO_TIMEOUT=1800
DISTCC_HOSTS=--localslots_cpp=4 127.0.0.1:3000/16,lzo 127.0.0.1:3001/16,lzo  127.0.0.1:3002/16,lzo 127.0.0.1:3003/16
CCACHE_PREFIX=1800
```

**Comment by shawnl** [comment]
I think the problem is not ccache, but that you are using 127.0.0.1 with a
port instead of "localhost". Localhost handling is special in distcc and
does not use the tcp protocol.
