### ISSUE TITLE
using distcc-workers behind a reverse proxy

### ISSUE THREAD

**Issue by MrD2** [distcc/distcc#400]
Hello,

I'm trying to use distcc workers behind a nginx reverse proxy. But the distcc cannot access the workers and it is stuck in the connecting state.

I tried using DISTCC_HOSTS both with url and IP. Same error happens on both.

As far as i know (or red) distcc keeps the connection alive, so there is no reason why the file is sent and then the connection is strip down

Does anybody had the same problem? Is there a better way of doing this?

**Comment by shawnl** [comment]
> I'm trying to use distcc workers behind a nginx reverse proxy

This cannot work. The distcc protocol is a TCP protocol and cannot work over HTTP.
