### ISSUE TITLE
Requesting the next version release

### ISSUE THREAD

**Issue by insujang** [distcc/distcc#401]
Thanks to the PR #371 built distcc from source code works well with Python version >=3.8, however, this commit not included in the latest packaged distcc v3.3.3.
As a result, when we install distcc via a package management system (e.g. rpm) distcc pump mode won't work with recent Python.

I tested on fedora:33 Docker container, and the same error in the issue #370 is out.

**Comment by shawnl** [comment]
@mitchblank If you can confirm that HEAD works with macOS I will release v3.3.4.

**Comment by mitchblank** [comment]
Builds completely clean for me with `./configure --without-libiberty --disable-pump-mode`

With pump mode the python extension gave me issues but I think that's just because I've upgraded Xcode since I last build Homebrew python so I don't believe that failure is distcc-related.

**Comment by mitchblank** [comment]
Had some more time to poke at this -- after reinstalling python I can build with `./configure --without-libiberty`

Homebrew drops in a private copy of libiberty when building distcc, so this should be fine: https://github.com/Homebrew/homebrew-core/blob/master/Formula/distcc.rb
