### ISSUE TITLE
distcc fails to find the native compiler 

### ISSUE THREAD

**Issue by asheplyakov** [distcc/distcc#426]
```
cat > hello.c <<-EOF
#include <stdio.h>
int main(int argc, char **argv) {
     printf("Hello, world!\n");
     return 0;
}
EOF
distcc gcc -Wall -std=gnu89 -I. -O2 -o hello.o -c hello.c
```

The output is:
```
free(): invalid next size (fast)
Aborted (core dumped)
```

There are two unrelated problems here:
1. distcc (or rather ` dcc_gcc_rewrite_fqn`) fails to find the native compiler due to autoconf idea about canonical system name (`x86_64-alt-linux-gnu`) being different from that of GCC (`x86_64-alt-linux`)
2. `dcc_gcc_rewrite_fqn` writes beyond the allocated memory (`newcmd`), see #425 for more details)

Also problem 1 occurs if the toolchain uses a slightly different triple (say, `aarch64-unknown-linux-gnu` instead of the expected `aarch64-linux-gnu`)

**Comment by asheplyakov** [comment]
> distcc (or rather dcc_gcc_rewrite_fqn) fails to find the native compiler due to autoconf idea about canonical system name (x86_64-alt-linux-gnu) being different from that of GCC (x86_64-alt-linux)

The same problem exists on Fedora (CentOS, RHEL):  gcc triplet is `x86_64-redhat-linux`, and configure identifies the system as `x86_64-pc-linux-gnu`

**Comment by shawnl** [comment]
This is all really ugly. I know that I am the one that added this cross-compile stuff, but GCC is really at fault here. When I met Andrew Pinsky the inferiorness in cross-compile compared to clang was admitted, but no-body has come forward with a canonicalization, and done the work.

I am not sure what distcc can do, as we are kind of at the butt end of the problem.

**Comment by asheplyakov** [comment]
> This is all really ugly. 

I agree.

> but GCC is really at fault here

Firstly those wonderful `${arch}-redhat-linux` triplets are sort of set in the stone (they have existed for more than 2 decades), so now it does not matter who/what is at fault.
Secondly just because GCC triplets are configurable doesn't mean it's GCC fault.

> I am not sure what distcc can do

What about guessing the correct triplet for distro/OS with `gcc -dumpmachine` (which is what this patch does)?

**Comment by asheplyakov** [comment]
> What about guessing the correct triplet for distro/OS with gcc -dumpmachine (which is what this patch does)?

`this patch` is #427

**Comment by asheplyakov** [comment]
Apparently with #426 distcc is able to run the native compiler.  `dcc_gcc_rewrite_fqn` is unable to figure out the compiler triple, and does not change the original `argv` in any way. So distcc runs `gcc` remotely.  Therefore I'm closing this issue.

 However cross rewriting does not work. Hence I'll file a different bug.
