### ISSUE TITLE
distccd does not listen

### ISSUE THREAD

**Issue by petaflot** [distcc/distcc#447]
distccd starts with no error but does not listen

```
# distccd --inetd --allow 172.16.100.0/24 --port 3632 --log-level debug --listen 172.16.100.11 -N 15
distccd[14052] (dcc_discard_root) successfully set no_new_privs
distccd[14052] (dcc_discard_root) discarded root privileges, changed to uid=240 gid=240
```
in another term:
```
# ifconfig | grep 172
        inet 172.16.100.11  netmask 255.255.255.0  broadcast 172.16.100.255
# netstat -ln | grep 3632
#
```

without an error message I could not solve it

**Comment by asheplyakov** [comment]
Works as designed.

`--inetd` is for running distccd from a network "super-server" (such as inetd, xinetd, etc).
In this mode distccd is not supposed to listen anything. Instead it processes the request from stdin, and sends the result to stdout.

**Comment by petaflot** [comment]
actually it does work. thanks for paraphrasing the doc :-s
