### ISSUE TITLE
[Question] Set compiler for volunteer.

### ISSUE THREAD

**Issue by TornaxO7** [distcc/distcc#473]
## Terms
- Client: The computer which starts the compilation
- Volunteers: The other computers which help to compile the prorgram

## The question
`Client` hast the gcc version 11.3 while the Volunteers have the gcc version 12.2. Luckily the Volunteers managed to install gcc-11-3 which is the gcc compiler with version 11.3. Now I'd like to know if it's possible to say to the distcc-daemons of the volunteers to use the `gcc-11-3` compiler instead of the `gcc` (version 12.2) compiler?

**Comment by sourcefrog** [comment]
I'd say the cleanest way to do this is to set the compiler name to include an explicit version, e.g. `CC="distcc gcc-11.3"`.

**Comment by TornaxO7** [comment]
okeydokey, thanks!
