### ISSUE TITLE
distccd creates zombie processes

### ISSUE THREAD

**Issue by gjvc** [distcc/distcc#478]
When using  CentOS7 (CentOS Linux release 7.9.2009 (Core)), distcc 3.2rc1 (as available from the EPEL repository) and distcc 3.4 (as compiled by me) both create zombie processes on the server side.  Is this ever expected?  When are they reaped?  Right now it seems that the slot, once occupied by a zombie, will be  used up indefinitely.

**versions**: 3.2rc1 and 3.4
**OS version**: CentOS Linux release 7.9.2009 (Core)

**Comment by gjvc** [comment]
This is not a bug in distcc.

Setting 
```
[Service]
Type=forking
```
in the systemd .service file corrects this. (The default value for `Type` is `simple`.)

It's probably worth including an example .service file to highlight this.

```
[Unit]
Description=Distccd A Distributed Compilation Server
After=network.target

[Service]
Type=forking
User=nobody
EnvironmentFile=-/etc/sysconfig/distccd
ExecStart=/usr/bin/distccd --daemon $OPTIONS

[Install]
WantedBy=multi-user.target
```

**Comment by sourcefrog** [comment]
Glad you worked it out. If you want to send a doc PR to add that somewhere appropriate that would be nice.

**Comment by george-cox** [comment]
I have looked further at this and there is definitely something wrong, because I still see zombie processes lingering, and I don't with the two-line fix posted here. https://lists.samba.org/archive/distcc/2023q1/004502.html
