### ISSUE TITLE
Feature request: add rust support

### ISSUE THREAD

**Issue by jpsollie** [distcc/distcc#482]
distcc supports clang and gcc on Gentoo, but with the increasing popularity of rust, would it be possible for distcc to support rust compiling?

**Comment by sourcefrog** [comment]
Just my opinion: I love Rust too, but the compilation model is so different to C/C++ that it may not make sense to add into distcc. Also, https://github.com/mozilla/sccache already exists and provides both distributed caching and distributed compilation.

**Comment by sourcefrog** [comment]
Closing because there are already different solutions for Rust, and I don't see much value in adding it to distcc. 

If anyone reading this is really interested in specifically adding it and has an idea how it would work, then feel free to reopen.
