### ISSUE TITLE
distcc causes compilation errors

### ISSUE THREAD

**Issue by gfim** [distcc/distcc#486]
**environment:**
distcc 3.4 and 3.3.3 (but not 3.2rc1)
Rocky 8 (both distcc client and server)
gcc 12 (from gcc-toolset-12 @appstream repo - both client and server)
cmake 3.20.2
ccache 3.7.7 (but also happens without ccache)
not using pump or masquerade

**build commands:**
cmake -DCMAKE_C_COMPILER_LAUNCHER='ccache;distcc' -DCMAKE_CXX_COMPILER_LAUNCHER='ccache;distcc' ..
make -j40

**distcc hosts file:**
distccd-server/20
localhost/7

**distccd server (hostname=distccd-server)**
distcc 3.3.3
Rocky 8
OPTIONS="--jobs 20 --allow xxx.xxx.xxx.xxx/24 --enable-tcp-insecure"

Compilation proceeds normally for a while. I can see that the compilations are being shared with the server distccd-server. And then suddenly we get thousands of compilation errors. The file that fails seems random - if I restart the make, it will proceed for a while and then fail at a different file. There are no errors if I compile without distcc. Removing ccache from the compilation doesn't make any difference. I've tried to create a simple test case to reproduce the problem, but I haven't been able to come up with one.

The first few lines of the errors always seem to be the same - see below (some details elided). Note that the "previously defined here" is the same file and line as the redefinition. It's as if the file has been duplicated as input to the compiler. I've tried turning on DISTCC_VERBOSE but I can't see anything obvious.

The only clue I have is that it seems to happen more if the server is heavily loaded. That makes me think that it's something to do with falling back to local compilation if the server has no slots available.

**Error messages**
In file included from /opt/rh/gcc-toolset-12/root/usr/include/c++/12/string:38,
                 from ...:
/opt/rh/gcc-toolset-12/root/usr/include/c++/12/x86_64-redhat-linux/bits/c++config.h:2549:15: error: redefinition of ‘void std::__terminate()’
 2549 |   inline void __terminate() _GLIBCXX_USE_NOEXCEPT
      |               ^~~~~~~~~~~
In file included from /opt/rh/gcc-toolset-12/root/usr/include/c++/12/type_traits:38,
                 from /usr/local/Qt-6.5.2/include/QtCore/qglobal.h:13,
                 from /usr/local/Qt-6.5.2/include/QtCore/qnamespace.h:12,
                 from /usr/local/Qt-6.5.2/include/QtCore/qobjectdefs.h:12,
                 from /usr/local/Qt-6.5.2/include/QtCore/qobject.h:10,
                 from /usr/local/Qt-6.5.2/include/QtCore/qabstracteventdispatcher.h:7,
                 from /usr/local/Qt-6.5.2/include/QtCore/QAbstractEventDispatcher:1,
                 from ...,
                 from <command-line>:
/opt/rh/gcc-toolset-12/root/usr/include/c++/12/x86_64-redhat-linux/bits/c++config.h:2549:15: note: ‘void std::__terminate()’ previously defined here
 2549 |   inline void __terminate() _GLIBCXX_USE_NOEXCEPT

**Comment by sourcefrog** [comment]
Hi, I can appreciate this is annoying, but I don't think anyone else can diagnose this without a reproduction case or more information, so I'm going to close it. If you do find more information, please reopen.
